[package]
name = "game2"
version = "0.1.0"
authors = ["Ivan Ivanov <ivan@ivanovs.info>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.34.0", features = ["bundled"] }
gl = { path = "lib/gl" }
nalgebra-glm = "0.7.0"
stb_image = "0.2.2"
thiserror = "1.0.18"
tobj = "2.0.0"
