[package]
name = "game2"
version = "0.1.0"
authors = ["Ivan Ivanov <ivan@ivanovs.info>"]
edition = "2018"

[dependencies]
glutin = "0.24.0"
gl = { path = "lib/gl" }
nalgebra-glm = "0.7.0"
stb_image = "0.2.2"
thiserror = "1.0.19"
gltf = "0.15.2"

[features]
default = []
debug = []
