[package]
name = "game2"
version = "0.1.0"
authors = ["Ivan Ivanov <ivan@ivanovs.info>"]
edition = "2018"

[dependencies]
glutin = "0.27.0"
gl = { path = "lib/gl" }
stb_image = "0.2.3"
thiserror = "1.0.19"
gltf = "0.16.0"
glam = "0.17.3"

[features]
default = []
debug = []
